/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.fuseanalytics.gradle

import com.fuseanalytics.aws.ecr.EcrToken
import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

class EcrTokenPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.fuseanalytics.gradle.ecrToken")

        then:
        project.hasProperty("ecrToken")
        EcrToken token = project.getProperties()["ecrToken"]?.get()
        assert token != null
        assert token.getUser() != null
        assert token.getPassword() != null
    }
}
